### ISSUE TITLE
Are you still accepting Pull Requests?

### ISSUE THREAD

**Issue by roark** [pluma0/ordered-hashmap#4]
Hi @pluma,

This is an awesome library and still has many great use cases. Although it is marked as 'unmaintained' I'm hoping you're still willing to accept pull requests. If you're willing to merge in the pull requests I submitted and publish an update to NPM that would be amazingly fantastic.

If you'd like a branch that already has all the pull requests rebased on top of one another, you can check out my forked master branch at [roark/ordered-hashmap](https://github.com/roark/ordered-hashmap)

I'm greatly enjoying this library and would love to see these items added. Many thanks and cheers!

**Comment by pluma** [comment]
Hi @roark,

thank you for your interest. Great to hear that you still find this module useful.

I don't have the time to continue maintaining this project and that includes publishing new releases.

However if you tell me your NPM username I can add you as a maintainer to the package so you can take over development if you want. I've added you as a collaborator to this repository if you want to continue development upstream.

Cheers,

Alan

**Comment by roark** [comment]
Hi Alan,

Thank you for adding me to the project, I'm enthused for the opportunity to maintain and continue any further development. My NPM username is **roark**.

Cheers

**Comment by pluma** [comment]
I've added you as a maintainer on NPM. Have fun! :wink:
